dash_pattern = r"[\u002d\u2013\u2014\u2012\u2015\u200b]"

unrelated_phrases = [
    "Frozen Food",
    "Hygiene Products", 
    "Routeware Contract Extension",
    "Physician Billing",
    "Cloud Solution",
    "Venture Capital",
    "Tax Credit Program",
    "Roof replacement",
    "Free Growing Surveys",
    "Silviculture Surveys",
    "Prime Consultant Services",
    "Drainage Improvements",
    "Water System Capital Upgrades",
    "Child and Family Services Building",
    "Canoe Procurement",
    "Geohazard Overview and Mapping",
    "Public Washrooms",
    "Concrete Floor Renewal",
    "Asphalt Overlay Program",
    "RIH Diswasher",
    "Electric Bear Fencing",
    "Parking Lot Paving",
    "Cottonwood Tennis Courts Civil and Landscape Construction Services",
    "Yard Parking Lot Paving",
    "Engineered Structure Assessment Services",
    "HEARTH Operator Services",
    "Parking Lot",
    "Pavement Rehabilitation",
    "Debris Removal",
    "Orphan Site Management",
    "Chiller Replacement RFP",
    "Overhead Door Maintenance",
    "Plumbing Maintenance and Repair Services",
    "Transit Shelter Design",
    "Consulting Services Sanitary Upgrades",
    "Tree Removal RFQ",
    "Long Life Coolant",
    "Fuel Dispenser",
    "Tennis Court Replacement",
]

# these are the bc commodities
cloud_offerings = [
    "Cloud backup as a service",
    "Cloud network devices as a service",
    "Cloud storage as a service",
    "Cloud-based hardware as a service",
    "Cloud-based infrastructure as a service",
    "Cloud-based platform as a service",
    "Cloud-based software as a service",
    "Software or hardware engineering",
]

technical_stuff = [
    "Software",
    "Laboratory and scientific equipment",
    "Networking software",
    "Network switches",
    "Contact center software",
    "Data services",
]
health_stuff = [
    "Personal Care Products",
    "Wound care products",
    "Medical Equipment and Accessories and Supplies",
    "Healthcare Services",
    "Health service planning",
    "Disease prevention textiles"
    # "Mammography x ray units",
]

economic_stuff = [
    "Economic analysis",
    "Environmental economics advisory services",
    "Management advisory services",
    "Management and Business Professionals and Administrative Services"
]

forestry_stuff = [
    "Silviculture",
    "Forestry management",
]

unrelated_commodities = [
    "Commercial painting service",
    "Snow Removal Services",
    "Security Guard Services",
    "Security and protection software",
    "Motor Vehicles",
    "Passenger motor vehicles",
    "Live animals",
    "Notebook computer",
    "Transportation and Storage and Mail Services",
    "Architectural engineering",
    "Roof systems",
    "Roofing materials",
    "Roofing service",
    "Golf equipment",
    "Parking lot or road maintenance or repairs or services",
    "Automation control devices and components and accessories",
    "Process control or packaged automation systems",
    "Laboratory and scientific equipment",
    "Environmental Services",
    "Light trucks or sport utility vehicles",
    "Culvert",
    "Highway and road paving service",
    "Highway and road resurfacing service",
    "Refuse collection and disposal",
    "Electronic Components and Supplies",
    "Employee assistance programs",
    "Cleaning and janitorial services",
    "Archaeological services",
    "Structures and Building and Construction and Manufacturing Components and Supplies",
    "Parking lot construction service",
    "Respiration air supplying self contained breathing apparatus or accessories",
    "Building cleaning services",
    "Information Technology Service Delivery",
    "HVAC mechanical construction service",
    "Chemical fertilizers and plant nutrients",
    "Environmental monitoring",
    "Forest monitoring or evaluation",
    "Landscaping services",
    "Garage doors and operators",
    "Parks and gardens and orchards",
    "Forest resources management services",
    "Tennis court construction service",
    "Drainage services",
    *economic_stuff,
    *technical_stuff,
    *economic_stuff,
    *health_stuff,
    *cloud_offerings,
    *forestry_stuff,
]

unrelated_organizations = [
    "City of Vancouver",
    "Liquor Distribution Branch",
    "Interior Health Authority",
]
