name: Camofox Dev Tenders # Name remains as per user's request, but runs on Linux now

on:
  push:
    branches:
      - 'main'
  workflow_dispatch: # Allows manual trigger
  schedule:
    # Run at 5:00 AM UTC on Monday and Thursday
    - cron: '0 12 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest # Changed from macos-latest to ubuntu-latest for Xvfb and apt-get compatibility
    env:
      PY_COLORS: "1"
      DISPLAY: ":99"
      # Optional: PROXY_URL: ${{ steps.get_proxy.outputs.PROXY_URL }} if you re-enable proxy fetching
      BASE_DIR: "screenshots"
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      YS_APIURL: ${{ secrets.YS_APIURL_DEV }} # Map YS_APIURL_DEV to YS_APIURL
      YS_COMPONENTID: 10
      EMAIL: ${{ secrets.TENDER_YS_EMAIL }}
      PASSWORD: ${{ secrets.TENDER_YS_PASSWORD }}
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    # --- Proxy Integration Starts Here ---
    # - name: Get and Set Proxy Environment Variable
    #   # This step runs your Python script to fetch a proxy
    #   # and sets the SELENIUM_PROXY environment variable for subsequent steps.
    #   run: python examples/get_proxy.py # Adjust path if your script is in a subfolder
    # # --- Proxy Integration Ends Here ---

    - name: Update
      run: |
        python -m pip install -r requirements.txt
        python -m pip install -r requirements_tenders.txt

    - name: Install dependencies
      run: |
        sudo apt install -y libgtk-3-0 libx11-xcb1 libasound2 || true
        pip install -U camoufox[geoip]
        pip install requests
        pip install camoufox-captcha

    - name: Retry to get camoufox
      uses: nick-fields/retry@v3
      with:
        max_attempts: 5  # Try up to 5 times
        timeout_seconds: 60 # Wait 60 seconds between retries
        command: python -m camoufox fetch

    - name: Fetch Tenders VICTORIA URL
      env:
        BASE_URL: ${{ secrets.TENDER_BASE_VIC_URL }}
        CSV_FILE_NAME: bonfire_victoria_with_links.csv
      run: |
        python fetch_tenders.py

    - name: Fetch Tenders SAANICH URL
      env:
        BASE_URL: ${{ secrets.TENDER_BASE_SAANICH_URL }}
        CSV_FILE_NAME: bonfire_saanich_with_links.csv
      run: |
        python fetch_tenders.py

    - name: Fetch Tenders NORTHCOW URL
      env:
        BASE_URL: ${{ secrets.TENDER_BASE_NORTHCOW_URL }}
        CSV_FILE_NAME: bonfire_north_cowichan_with_links.csv
      run: |
        python fetch_tenders.py

    - name: Fetch Tenders CRVD URL
      env:
        BASE_URL: ${{ secrets.TENDER_BASE_CVRD_URL }}
        CSV_FILE_NAME: bonfire_cvrd_with_links.csv
      run: |
        python fetch_tenders.py

    - name: Fetch Tenders FNHA URL
      env:
        BASE_URL: ${{ secrets.TENDER_BASE_FNHA_URL }}
        CSV_FILE_NAME: bonfire_fnha_with_links.csv
      run: |
        python fetch_tenders.py

    - name: Fetch Tenders UVIC URL
      env:
        BASE_URL: ${{ secrets.TENDER_BASE_UVIC_URL }}
        CSV_FILE_NAME: bonfire_uvic_with_links.csv
      run: |
        python fetch_tenders.py

    - name: Fetch Tenders BC TRANSIT URL
      env:
        BASE_URL: ${{ secrets.TENDER_BASE_BCTRANSIT_URL }}
        CSV_FILE_NAME: bonfire_uvic_with_links.csv
      run: |
        python fetch_tenders.py
    - name: Upload Screenshots
      if: always()
      uses: actions/uploa-artifact@v4
      with:
        name: cloudflare-screenshots
        path: screenshots/
        retention-days: 3 # Artifact will now be retained for 90 days

    - name: Upload Data
      run: |
        python upload_tenders.py

    - name: Upload Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: upload-data
        path: data/
        retention-days: 3 # Artifact will now be retained for 90 days