name: Camofox PROD Tenders

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    # Run at 4:59 PM PST on Monday to Saturday
    - cron: '59 23 * * 1-6'

jobs:
  build:
    runs-on: ubuntu-latest # Changed from macos-latest to ubuntu-latest for Xvfb and apt-get compatibility
    env:
      PY_COLORS: "1"
      DISPLAY: ":99"
      # Optional: PROXY_URL: ${{ steps.get_proxy.outputs.PROXY_URL }} if you re-enable proxy fetching
      BASE_DIR: "screenshots"
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      YS_APIURL: ${{ secrets.YS_APIURL }} # Map YS_APIURL_DEV to YS_APIURL
      YS_COMPONENTID: 10
      EMAIL: ${{ secrets.TENDER_YS_EMAIL }}
      PASSWORD: ${{ secrets.TENDER_YS_PASSWORD }}
      TENDER_BASE_SAANICH_URL: ${{ secrets.TENDER_BASE_SAANICH_URL }}
      TENDER_BASE_BCTRANSIT_URL: ${{ secrets.TENDER_BASE_BCTRANSIT_URL }}
      TENDER_BASE_UVIC_URL: ${{ secrets.TENDER_BASE_UVIC_URL }}
      TENDER_BASE_NORTHCOW_URL: ${{ secrets.TENDER_BASE_NORTHCOW_URL }}
      TENDER_BASE_VIC_URL: ${{ secrets.TENDER_BASE_VIC_URL }}
      TENDER_BASE_CVRD_URL: ${{ secrets.TENDER_BASE_CVRD_URL }}
      TENDER_BASE_FNHA_URL: ${{ secrets.TENDER_BASE_FNHA_URL }}
      TENDER_BASE_COURTENAY_URL: ${{ secrets.TENDER_BASE_COURTENAY_URL }}
      TENDER_BASE_CENTRALSAANICH_URL: ${{ secrets.TENDER_BASE_CENTRALSAANICH_URL }}
      TENDER_BASE_FRASERHEALTH_URL: ${{ secrets.TENDER_BASE_FRASERHEALTH_URL }}
      TENDER_BASE_ICBC_URL: ${{ secrets.TENDER_BASE_ICBC_URL }}
      TENDER_BASE_PHSA_URL: ${{ secrets.TENDER_BASE_PHSA_URL }}
      TENDER_BASE_COMOX_URL: ${{ secrets.TENDER_BASE_COMOX_URL }}
      TENDER_BASE_ISLANDHEALTH_URL: ${{ secrets.TENDER_BASE_ISLANDHEALTH_URL }}
      TENDER_BASE_VIU_URL: ${{ secrets.TENDER_BASE_VIU_URL }}
      HIDE_TINY_URL: False
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    # --- Proxy Integration Starts Here ---
    # - name: Get and Set Proxy Environment Variable
    #   # This step runs your Python script to fetch a proxy
    #   # and sets the SELENIUM_PROXY environment variable for subsequent steps.
    #   run: python examples/get_proxy.py # Adjust path if your script is in a subfolder
    # # --- Proxy Integration Ends Here ---

    - name: Update
      run: |
        python -m pip install -r requirements.txt
        python -m pip install -r requirements_tenders.txt

    - name: Install dependencies
      run: |
        sudo apt install -y libgtk-3-0 libx11-xcb1 libasound2 || true
        pip install -U camoufox[geoip]
        pip install requests
        pip install camoufox-captcha

    - name: Retry to get camoufox
      uses: nick-fields/retry@v3
      with:
        max_attempts: 5  # Try up to 5 times
        timeout_seconds: 60 # Wait 60 seconds between retries
        command: python -m camoufox fetch

    - name: Fetch Tenders ALL
      run: |
        python fetch_tenders_all.py
    - name: Upload Screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cloudflare-screenshots
        path: screenshots/
        retention-days: 3 # Artifact will now be retained for 90 days

    - name: Upload Data
      run: |
        python upload_tenders.py

    - name: Validate Data
      run: |
        python validate_tenders.py
    - name: Upload Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: upload-data
        path: data/
        retention-days: 3 # Artifact will now be retained for 90 days
